<?php
/* Author: */

$labels = array();
$labels['buttonjunk'] = 'Rapporter comme spam';
$labels['markasjunk'] = 'Rapporter comme spam';
$labels['buttonnotjunk'] = 'Marquer comme msg légitime';
$labels['markasnotjunk'] = 'N\'est pas du spam';
$labels['notjunk'] = 'Msg légitime';
$labels['junk'] = 'Pourriel';

$messages = array();
$messages['reportedasjunk'] = 'Message classé comme spam';
$messages['reportedasnotjunk'] = 'Message classé comme légitime';

?>
